config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"} 
  resources :admin do 
    collection do
      get 'store_timing'
      get 'pricing'
      get 'announcement'
    end
  end

  get 'welcome/index'
  put 'update_store_hours' => 'admin#update_store_hours'

  root 'welcome#index'
  get 'about' => 'static#about'
  get 'services' => 'static#services'
  get 'locations' => 'static#locations'
  get 'contacts' => 'static#contacts'
  get 'resources' => 'static#resources'
  get 'privacy_policy' => 'static#privacy_policy'
  post 'create_contacts' => 'static#create_contacts'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/store_hour.rb
class StoreHour < ActiveRecord::Base
  default_scope { order(created_at: :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

   before_action :authenticate_user!


	layout 'admin'

	def index
	end

	def store_timing
        @store_hours = StoreHour.limit(7)
	end

    def update_store_hours
        @store_hours = StoreHour.limit(7)
        @store_hours.each_with_index do |week_day, index|
        # byebug
        week_day.update_attributes(:opening_time => params[:"opening_time_#{index}"], :closing_time => params[:"closing_time_#{index}"], :is_closed => params[:"is_closed_#{index}"])
        end
        redirect_to (:back), notice: "Store Hours updated successfully"
    end

    def pricing
    end
    	
    def announcement
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(users)
    admin_index_path
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	layout 'admin'

end 

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	layout 'admin'

end 

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about
  end

  def locations
  end

  def services
  end

  def resources
  end

  def contacts
    @contact = Contact.new
    @store_hours = StoreHour.limit(7)
  end

  def create_contacts
    post_params = params[:post]
    Contact.create(:name => post_params[:name], :email => post_params[:email], :phone => post_params[:phone], 
                   :message => post_params[:message])
    UserMailer.thanking_email_to_visitor(post_params[:email], post_params[:name]).deliver
    UserMailer.notify_email_to_admin(post_params[:email], post_params[:message]).deliver

    respond_to do |format|
      format.js
    end
  end


  def privacy_policy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/announcement.html.erb
announcement

app/views/admin/index.html.erb
Welcome!

app/views/admin/pricing.html.erb
pricing

app/views/admin/store_timing.html.erb
<h2>Set Store Hours</h2>


<%= form_tag update_store_hours_path, :class => "form-inline", :method => :put do %>

	<% @store_hours.each_with_index do |week_day, index| %>
	<div style="margin-bottom: 10px;">
	    <div class="form-group">
	    <label for="Week day" style="font-size: 19px; width: 130px;"><%= week_day.day %></label>
	    <!-- <input type="email" class="form-control" id="email"> -->
	    </div>		
		<%#= week_day.day %>
	

		<%#= check_box_tag(:"is_closed_#{week_day.id}", week_day.is_closed, week_day.is_closed) %>
	    <div class="form-group">
	      Opening Time:
		  <%= text_field_tag(:"opening_time_#{index}", week_day.opening_time, :class => "form-control") %>

	      <!-- <input type="email" class="form-control" id="email"> -->
	    </div>		
		<%#= text_field_tag(:"opening_time_#{week_day.id}", week_day.opening_time) %>
	    <div class="form-group">
	      Closing Time:
		  <%= text_field_tag(:"closing_time_#{index}", week_day.closing_time, :class => "form-control") %>

	      <!-- <input type="email" class="form-control" id="email"> -->
	    </div>	
	    <div class="checkbox">
	      <label>
		    <%= check_box_tag(:"is_closed_#{index}", week_day.is_closed, week_day.is_closed) %>
		    <b>Closed</b>(if checked, store timings will not be displayed)
	      </label>
	    </div>		    		
		<%#= text_field_tag(:"closing_time_#{week_day.id}", week_day.closing_time) %>
		<%#= time_field_tag(:task, week_day.opening_time) %>
		<%= hidden_field_tag(:"day_id_#{index}", week_day.id) %>
		<br>
		</div>
	<% end %>
  <div>
  <!-- <button type="submit" class="btn btn-default">Submit</button> -->
  </br>
  <%= submit_tag 'Submit', :class=>"btn btn-default" %>
  	
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!--========================================================
                          FOOTER
=========================================================-->
<footer id="footer" class="footer">
    <div class="container">
        <div class="copyright wow fadeInUp" data-wow-delay="0.4s">
            Self Storage Company © <span id="copyright-year"></span> All rights reserved. Terms of use |
            <%= link_to 'Privacy Policy', privacy_policy_path %>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!--========================================================
                          HEADER
=========================================================-->
<header id="header" class="header">
    <div id="stuck_container" class="stuck_container">
        <div class="container">
            <div class="header_panel">
                <div class="brand">
                    <h1 class="brand_name">
                        <a href="./">SHORTY'S STORAGE</a>
                    </h1>
                </div>

                <nav class="nav">
                    <ul class="sf-menu">
                        <li class="<%= active_class(root_path) %>">
                            <%= link_to 'Home', root_path %>
                        </li>
                        <li class="<%= active_class(about_path) %>">
                            <%= link_to 'About', about_path %>
                        </li>
                        <!--<li class="<%= active_class(locations_path) %>">-->
                            <!--<%= link_to 'Locations', locations_path %>-->
                        <!--</li>-->
                        <li class="<%= active_class(services_path) %>">
                            <%= link_to 'Storage', services_path %>
                        </li>
                        <li class="<%= active_class(resources_path) %>">
                            <%= link_to 'Resources', resources_path %>
                        </li>
                        <li class="<%= active_class(contacts_path) %>">
                            <%= link_to 'Contacts', contacts_path %>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shortystorage</title>
  <meta charset="utf-8">
  <meta name="format-detection" content="telephone=no"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">

<style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <!-- <a class="navbar-brand" href="#">Logo</a> -->
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

      <% if user_signed_in? %>
          <!-- Logged in as <strong><%#= current_user.email %></strong>. -->
          <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> <!-- | -->
          <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'active'  %> <!-- | -->
          
          <li><%= link_to "Store Timing", store_timing_admin_index_path, :class => 'active'  %></li>
          <li><%= link_to "Pricing", pricing_admin_index_path  %></li>
          <li><%= link_to "Announcement", announcement_admin_index_path %></li>


      <% end %>

<!--         <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Projects</a></li>
        <li><a href="#">Contact</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'active' %></li> 

            <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li> 
          <li><%= link_to "Login", new_user_session_path %></li> 
<% end %>
        <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav" style="width: 3%;">
<!--       <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-8 text-left" style="width: 95%;"> 


    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

    </div>

  </div>
</div>



    <%#= render '/layouts/footer' %>
  <%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shortystorage</title>
  <meta charset="utf-8">
  <meta name="format-detection" content="telephone=no"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">

</head>
<body>
  <div class="page">

    <%= render '/layouts/header' %>

    <%= yield %>

    <%= render '/layouts/footer' %>
  </div>
  <%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
</body>

</html>

app/views/welcome/index.html.erb
<!--========================================================
                          CONTENT
=========================================================-->
<section id="content" class="content">

    <div class="parallax parallax1">
        <div class="container center wow fadeInUp" data-wow-delay="0.4s">
            <h2>Be Assured That Your Valuables Are <br/>
                in the Right Place </h2>

            <!--<form id="search" class="search-form" action="search.php" method="GET"-->
                  <!--accept-charset="utf-8">-->
                <!--<label class="input box-rsh" for="in">-->
                    <!--<input class="" id="in" type="text" name="s" placeholder="Search.."/>-->
                <!--</label>-->
                <!--<button class="box-rsh" type="submit">search</button>-->
            <!--</form>-->
        </div>
    </div>

    <div class="container well">
        <div class="row">
            <div class="grid_4 wow fadeInLeft" data-wow-delay="0.4s">
                <div class="box2" data-equal-group="1">
                    <div class="box2_aside">
                        <div class="number">1</div>
                    </div>
                    <div class="box2_cnt">
                        <h4>
                            <a href='#'>Providing high quality
                                        storage experience
                            </a>
                        </h4>
                    </div>
                    <p>​Our fully packed and graded gravel lot is maintained all year round; don’t get stuck at other lots or rust your underbody on wet grass.</p>
                </div>
            </div>
            <div class="grid_4 wow fadeInUp" data-wow-delay="0.8s">
                <div class="box2" data-equal-group="1">
                    <div class="box2_aside">
                        <div class="number">2</div>
                    </div>
                    <div class="box2_cnt">
                        <h4>
                            <a href='#'>RV Storage & Parking Stalls
                            </a>
                        </h4>
                    </div>
                    <p>We offer a total care approach! We hope you find everything you need, Shorty’s Storage is focused on providing high-quality service and customer satisfaction – we will do everything we can to meet your expectations.</p>
                </div>
            </div>
            <div class="grid_4 wow fadeInRight" data-wow-delay="0.6s">
                <div class="box2" data-equal-group="1">
                    <div class="box2_aside">
                        <div class="number">3</div>
                    </div>
                    <div class="box2_cnt">
                        <h4>
                            <a href='#'>Make your move as easy
                                        as it should be
                            </a>
                        </h4>
                    </div>
                    <p>Pellentesque sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nulla
                       vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis.</p>
                </div>
            </div>
        </div>
    </div>

  <div class="bg-secondary center wow fadeInRight" data-wow-delay="0.6s">
    <div class="container well3">
      <h3>Annual Contract Discounts</h3>

      <p class="off2">Sign-up for Annual Contracts and get 20% off on Monthly Prices.</p>
      <a class="btn off1 box-rsh" href='#'>Read More</a>
    </div>
  </div>
    <div class="container well">
        <h2 class="center wow fadeInUp" data-wow-delay="0.4s">How RV Storage and Self Storage Works</h2>

        <div class="row off1 center-767">
            <div class="grid_3 wow fadeInRight" data-wow-delay="0.8s">
                <a class="icon-box" href='#'>
                    <h4>Find a location</h4>
                    <img src="assets/page-1_img02.jpg" alt=""/></a>
            </div>
            <div class="grid_3 wow fadeInRight" data-wow-delay="0.6s">
                <a class="icon-box" href='#'>
                    <h4>Select a unit size</h4>
                    <img src="assets/page-1_img03.jpg" alt=""/></a>
            </div>
            <div class="grid_3 wow fadeInRight" data-wow-delay="0.4s">
                <a class="icon-box" href='#'>
                    <h4>Reserve it online</h4>
                    <img src="assets/page-1_img04.jpg" alt=""/></a>
            </div>
            <div class="grid_3 wow fadeInRight" data-wow-delay="0.2s">
                <a class="icon-box" href='#'>
                    <h4>Your Account</h4>
                    <img src="assets/page-1_img05.jpg" alt=""/></a>
            </div>
        </div>
        <!--<div class="row off1">-->
            <!--<div class="grid_6 wow fadeInLeft" data-wow-delay="0.4s">-->
                <!--<h2>RV and Storage Facility</h2>-->
                <!--<iframe class="video off1" src="//player.vimeo.com/video/37582125?wmode=transparent"-->
                        <!--allowfullscreen></iframe>-->
                <!--<h4>Secure and convenient RV storage in Calgary</h4>-->
            <!--</div>-->
            <!--<div class="grid_6 wow fadeInRight" data-wow-delay="0.4s">-->
                <!--<h2>Testimonials</h2>-->
                <!--<blockquote class="off2"><img src="assets/page-1_img06.jpg" alt=""/>-->

                    <!--<div class="bq_cnt">-->
                        <!--<p><cite>Linda Grey</cite> — “Fusce euismod consequat ante. Lorem ipsum dolor sit-->
                                                   <!--amet, consectetuer adipiscing elit. Pellentesque sed dolor.-->
                                                   <!--Aliquam congue fermentum nisl… ”</p>-->
                    <!--</div>-->
                <!--</blockquote>-->
                <!--<blockquote><img src="assets/page-1_img07.jpg" alt=""/>-->

                    <!--<div class="bq_cnt">-->
                        <!--<p><cite>Sam Adams</cite> — “Seusce euismod consequat ante. Lorem ipsum dolor sit-->
                                                  <!--amet, consectetuer adipiscing elit. Pellentesque sed dolor.-->
                                                  <!--Aliquam congue fermentum nis...”</p>-->
                    <!--</div>-->
                <!--</blockquote>-->
                <!--<blockquote><img src="assets/page-1_img08.jpg" alt=""/>-->

                    <!--<div class="bq_cnt">-->
                        <!--<p><cite>Dan Thomson </cite> — “Fusce euismod consequat ante. Lorem ipsum dolor sit-->
                                                     <!--amet, consectetuer adipiscing elit. Pellentesque sed dolor.-->
                                                     <!--Aliquam congue fermentum nisl...”</p>-->
                    <!--</div>-->
                <!--</blockquote>-->
            <!--</div>-->
        <!--</div>-->
    </div>

  <div class="bg-orange">
    <div class="container well3">
      <h3 class="wow fadeInUp" data-wow-delay="0.4s">Benefits of Self Storage</h3>

      <div class="row center off1 wow fadeInUp" data-wow-delay="0.6s">
        <div class="grid_2">
          <div class="fact"><img src="./assets/page-2_img01.png" alt=""/>
            <h4>Free <br/>
              reservations</h4>
          </div>
        </div>
        <div class="grid_2">
          <div class="fact"><img src="./assets/page-2_img02.png" alt=""/>
            <h4>No long-term
              commitment</h4>
          </div>
        </div>
        <div class="grid_2">
          <div class="fact">
            <div class="fact_cnt">
              <h2>40+</h2>

              <p>Years</p>
            </div>
            <h4>Over 40 years of
              experience</h4>
          </div>
        </div>
        <div class="grid_2">
          <div class="fact">
            <div class="fact_cnt">
              <h2>365</h2>

              <p>Days a Year</p>
            </div>
            <h4>Access
              365 days a year</h4>
          </div>
        </div>
        <div class="grid_2">
          <div class="fact"><img src="assets/page-2_img03.png" alt=""/>
            <h4>Climate-controlled
              units</h4>
          </div>
        </div>
        <div class="grid_2">
          <div class="fact"><img src="assets/page-2_img04.png" alt=""/>
            <h4>Variety of
              unit sizes</h4>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="container well2">
        <h3 class="primary wow fadeInUp" data-wow-delay="0.4s">We pride ourselves on making self storage simple and affordable.
                            We offer safe, clean and convenient self storage rentals in your area.</h3>

        <div class="row off1 wow fadeInRight" data-wow-delay="0.6s">
            <div class="grid_4">
                <div class="box3">
                    <h4>
                        <a href='#'>Vechile Storage</a>
                    </h4>
                    <p class="off1">Our parking storage facility is ideal for your RV, Trailer, Motor Home, Utility Trailer, Truck, Car, Boat or Vehicle.  Park on a packed gravel lot with assigned stalls and 24hr access with onsite security.</p>
                </div>
            </div>
            <div class="grid_4">
                <div class="box3">
                    <h4>
                        <a href='#'>Self Storage</a>
                    </h4>
                    <p class="off1">Use our secure 8' wide and 8' tall lockable Cor-Ten steel storage containers to store your possessions or for business storage with 24hr access and onsite security. </p>
                </div>
            </div>
            <div class="grid_4">
                <div class="box3">
                    <h4>
                        <a href='#'>Access to On-Site Septic Dump</a>
                    </h4>
                    <p class="off1">Free Access to on-site septic dump for all customers, we also have on-site store for essentials needed for Vechiles and Storage units.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="bg-primary">
        <div class="container well3">
            <div class="row">
                <div class="grid_4 wow fadeInUp" data-wow-delay="0.4s">
                    <h3>Our Advantages</h3>

                    <p class="off2">Our self storage units and RV storage stalls are made with the intention to ensure that your investments are kept secure and in top condition throughout the year.</p>
                    <a class="btn off1 box-rsh" href='#'>read more</a>
                </div>
                <div class="grid_4 wow fadeInUp" data-wow-delay="0.8s">
                    <h3>24 x 7 Access</h3>

                    <p class="off2">Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer
                                    adipiscing elit. Pellentesque sed dolor. Aliquam congue fermentum nisl. Mauris
                                    accumsan nulla vel diam.</p>
                    <a class="btn off1 box-rsh" href='#'>read more</a>
                </div>
                <div class="grid_4 wow fadeInUp" data-wow-delay="0.6s">
                    <h3>About Us</h3>

                    <p class="off2">Locally owned and operated in Calgary, Shorty’s Storage is a family owned business that offers high end storage facilities.</p>

                    <a class="btn off1 box-rsh" href='#'>read more</a>
                </div>
            </div>
        </div>
    </div>



</section>